using System;
using System.ComponentModel;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;
using Windows.Win32;
using Windows.Win32.Security;
using Windows.Win32.System.JobObjects;

namespace Lithnet.Ecma2Framework.Shim
{
    /// <summary>
    /// Wraps a Windows Job Object and configures it with the
    /// <c>JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE</c> flag so that all processes
    /// assigned to the job are automatically terminated when this instance is
    /// disposed (i.e. when the shim process exits or explicitly releases the handle).
    /// </summary>
    /// <remarks>
    /// The Win32 APIs used here are generated by CsWin32 from NativeMethods.txt;
    /// no hand-rolled P/Invoke declarations are present in this assembly.
    /// </remarks>
    internal sealed class JobObject : IDisposable
    {
        private SafeFileHandle jobHandle;
        private bool disposed;

        /// <summary>
        /// Creates a new Job Object and configures it with
        /// <c>JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE</c>.
        /// Throws <see cref="Win32Exception"/> if either Win32 call fails.
        /// </summary>
        public JobObject()
        {
            this.jobHandle = CreateHandle();
            ApplyKillOnCloseLimit(this.jobHandle);
        }

        /// <summary>
        /// Assigns the process identified by the supplied handle to this job object.
        /// Any child processes it spawns will also belong to the job.
        /// Throws <see cref="Win32Exception"/> if the assignment fails.
        /// </summary>
        /// <param name="processHandle">A handle to the process to assign (with PROCESS_SET_QUOTA and PROCESS_TERMINATE access).</param>
        public void Assign(SafeHandle processHandle)
        {
            if (processHandle == null)
            {
                throw new ArgumentNullException("processHandle");
            }

            if (!PInvoke.AssignProcessToJobObject(this.jobHandle, processHandle))
            {
                throw new Win32Exception(Marshal.GetLastWin32Error(), "AssignProcessToJobObject failed.");
            }
        }

        /// <inheritdoc/>
        public void Dispose()
        {
            if (this.disposed)
            {
                return;
            }

            this.disposed = true;

            // Closing the job handle triggers JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE,
            // which terminates all processes still assigned to the job.
            if (this.jobHandle != null && !this.jobHandle.IsInvalid && !this.jobHandle.IsClosed)
            {
                this.jobHandle.Dispose();
            }
        }

        // -------------------------------------------------------------------------
        // Private helpers
        // -------------------------------------------------------------------------

        private static SafeFileHandle CreateHandle()
        {
            // lpJobAttributes=null → default security, not inherited.
            // lpName=null         → anonymous job object.
            SafeFileHandle handle = PInvoke.CreateJobObject((SECURITY_ATTRIBUTES?)null, (string)null);

            if (handle.IsInvalid)
            {
                throw new Win32Exception(Marshal.GetLastWin32Error(), "CreateJobObject failed.");
            }

            return handle;
        }

        private static unsafe void ApplyKillOnCloseLimit(SafeFileHandle handle)
        {
            JOBOBJECT_EXTENDED_LIMIT_INFORMATION info = new JOBOBJECT_EXTENDED_LIMIT_INFORMATION();
            info.BasicLimitInformation.LimitFlags = JOB_OBJECT_LIMIT.JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE;

            bool success = PInvoke.SetInformationJobObject(
                handle,
                JOBOBJECTINFOCLASS.JobObjectExtendedLimitInformation,
                &info,
                (uint)Marshal.SizeOf(info));

            if (!success)
            {
                throw new Win32Exception(Marshal.GetLastWin32Error(), "SetInformationJobObject failed.");
            }
        }
    }
}
